#
# Makefile for the arch/vax/mm
#
# Note! Dependencies are done automagically 
# DON'T put your own dependencies here
# unless it's something special (ie not a .c file).

obj-y   := init.o pgtable.o pgalloc.o ioremap.o fault.o

